ERRORS:dict[int, str] = { 
	273: "Screen captures during Remote Desktop may not work properly.",
	270: "In order to trigger, multiscope acquisitions require the trigger source to be displayed.",
	269: "In order to trigger, multiscope acquisitions require an active channel per frame.",
	268: "In order to trigger, all frames must be connected.",
	217: "The Disk Save was Cancelled.",
	183: "Trigger is broken.",
	169: "Mask align failed, either no trigger or lost trigger. The mask test mask alignment feature was not able to succeed.",
	168: "Mask align failed, eye not well defined in waveform. The mask test mask alignment feature was not able to succeed.",
	167: "Mask align failed, waveform clipped or off screen. The mask test mask alignment feature was not able to succeed.",
	166: "Mask align failed, could not find pulse in waveform. The mask test mask alignment feature was not able to succeed.",
	165: "Non-differential transfer function is being applied to differential channels.",
	164: "Mask align failed because more than one channel is on.",
	161: "Infiniium's probe calibration data has been upgraded. The default values are being used.",
	160: "Mask align completed with mask failures. The mask test mask alignment feature completed but resultant fit gives mask failures.",
	159: "Stop mask testing to change control value. The mask test mask alignment feature completed but eye period exceeds delta T by at least",
	150: "Operation permitted for standard masks only. Auto fit works for standard masks only.",
	143: "Please turn on color grade (in the Display dialog) for this measurement.",
	141: "Please turn on a waveform of the type required for this measurement. There are no valid signals for this measurement.",
	140: "Exceeded maximum ASCII list length. When reading in an ASCII waveform, the maximum number of points was exceeded.",
	136: "The waveform is too large to be loaded due to memory constraints.",
	130: "Infiniium is unable to recover a clock. Adjust loop bandwidth.",
	129: "Too many vertices. There are too many data points in a mask test polygon.",
	128: "Mask test errors",
	126: "Waveform is clipped: Instrument setup is unchanged. Autoscale fails because the signal is too big to fit on the screen. ",
	125: "There is something in the header that Infiniium was not able to parse.",
	120: "Execution not possible: Calibration does not match mainframe.",
	117: "The waveform is too large to save as the selected file type.",
	116: "The waveform received has more points than expected. The extra points were discarded.",
	115: "Debug already in use.",
	113: "This directory is not valid.",
	112: "Unknown file type.",
	111: "Infiniium was unable to write to the file. The file may be read-only.",
	109: "Unable to read the disk: The disk might not be formatted.",
	108: "The disk is write protected.",
	107: "Infiniium could not find the destination disk.",
	88: "Self Test Warning: Please re-calibrate the instrument and re-run the self test.",
	85: "Combined filter too long to run. Please disable one or more filters. The combined FIR Filter is too long to run.",
	79: "Probe calibration error found! The attenuation (or gain) exceeds the limits.",
	74: "A Quick Env Cal is required.",
	72: "Infiniium has an internal error. Service is required. Calibration factors were unable to be saved to the disk.",
	68: "Infiniium is not calibrated! Please perform calibration before making measurements.",
	59: "Overload detected! Infiniium changed the impedance and scale. A channel overload condition occured. Protective changes were automatically performed.",
	50: "General failure to read disk",
	41: "Waveform data is not valid.",
	40: "This command can't be performed on the selected waveform. The selected operation cannot be performed on the selected waveform.",
	39: "The chosen function can't be performed on the selected waveform. The selected function cannot be performed on the selected waveform.",
	38: "The measurement you chose can't be performed on the selected waveform. The selected measurement cannot be performed on the selected waveform.",
	31: "Sorry, you can't make this measurement on the selected source. There was an attempt to drag-and-drop a measurement on an invalid source for the measurement.",
	30: "Infiniium is running remotely right now. The instrument is not listening to local commands. It is listening only to remote commands.",
	26: "This entry isn't valid. The control has been set to its default value.",
	25: "This entry isn't a valid selection. The control has not been modified.",
	24: "Control is at its maximum value. An out of range value was entered.",
	22: "Control is at its minimum value. An out of range value was entered.",
	15: "The requested GPIB operation can't be performed. This is a generic SCPI error that the requested operation cannot be performed.",
	11: "Signal amplitude too small to build the Real Time Eye. Increase vertical sensitivity.",
	8: "This function can't be performed on a peak detect waveform. The function requested is not permitted on peak detect waveforms.",
	7: "Mask align failed. The mask test mask alignment feature was not able to succeed.",
	6: "File not compatible with destination signal type. This happens when an internal signal is read from disk and its format is not recognized.",
	1: "Phase noise error. Check phase noise configuration.",
	0: "No error The error queue is empty. Every error in the queue has been read (:SYSTem:ERRor? query) or the queue was cleared by power-up or *CLS.",
	100: "Command error This is the generic syntax error used if the oscilloscope cannot detect more specific errors.",
	101: "Invalid character A syntactic element contains a character that is invalid for that type.",
	102: "Syntax error An unrecognized command or data type was encountered.",
	103: "Invalid separator The parser was expecting a separator and encountered an illegal character.",
	104: "Data type error The parser recognized a data element different than one allowed.",
	105: "GET not allowed A Group Execute Trigger was received within a program message.",
	108: "Parameter not allowed More parameters were received than expected for the header.",
	109: "Missing parameter Fewer parameters were received than required for the header.",
	112: "Program mnemonic too long The header or character data element contains more than twelve characters.",
	113: "Undefined header The header is syntactically correct, but it is undefined for the oscilloscope.",
	121: "Invalid character in number An invalid character for the data type being parsed was encountered.",
	123: "Numeric overflow Number is too large or too small to be represented internally.",
	124: "Too many digits The mantissa of a decimal numeric data element contained more than 255 digits excluding leading zeros.",
	128: "Numeric data not allowed A legal numeric data element was received, but the oscilloscope does not accept one in this position for the header.",
	131: "Invalid suffix The suffix does not follow the syntax described in IEEE 488.2 or the suffix is inappropriate for the oscilloscope.",
	138: "Suffix not allowed A suffix was encountered after a numeric element that does not allow suffixes.",
	141: "Invalid character data Either the character data element contains an invalid character or the particular element received is not valid for the header.",
	144: "Character data too long",
	148: "Character data not allowed A legal character data element was encountered where prohibited by the oscilloscope.",
	150: "String data error This error can be generated when parsing a string data element.",
	151: "Invalid string data A string data element was expected, but was invalid for some reason. For example, an END message was received before the terminal quote character.",
	158: "String data not allowed A string data element was encountered but was not allowed by the oscilloscope at this point in parsing.",
	160: "Block data error This error can be generated when parsing a block data element.",
	161: "Invalid block data",
	168: "Block data not allowed A legal block data element was encountered but was not allowed by the oscilloscope at this point in parsing.",
	170: "Expression error This error can be generated when parsing an expression data element.",
	171: "Invalid expression",
	178: "Expression data not allowed",
	200: "Execution error",
	212: "Arm ignored",
	213: "Init ignored",
	214: "Trigger deadlock",
	215: "Arm deadlock",
	220: "Parameter error",
	221: "Settings conflict",
	222: "Data out of range",
	223: "Too much data",
	224: "Illegal parameter value",
	230: "Data corrupt or stale",
	231: "Data questionable",
	240: "Hardware error",
	241: "Hardware missing",
	250: "Mass storage error",
	251: "Missing mass storage",
	252: "Missing media",
	253: "Corrupt media",
	254: "Media full",
	255: "Directory full",
	256: "File name not found",
	257: "File name error",
	258: "Media protected",
	260: "Expression error",
	261: "Math error in expression",
	300: "Device specific error",
	310: "System error",
	311: "Memory error",
	312: "PUD memory error",
	313: "Calibration memory lost",
	314: "Save/recall memory lost",
	315: "Configuration memory lost",
	321: "Out of memory",
	330: "Self-test failed",
	350: "Queue overflow",
	370: "No sub tests are defined for the selected self test",
	371: "Self Test status is corrupt or no self test has been executed.",
	372: "This product configuration does not support the requested self test.",
	373: "This product configuration does not support the requested source.",
	374: "The requested self test log file could not be found.",
	375: "Attenuator relay actuation counts can only be modified during factory service.",
	400: "Query error",
	410: "Query interrupted",
	420: "Query unterminated",
	430: "Query deadlocked",
	440: "Query unterminated after indefinite response"
}